### ISSUE TITLE
Metrics tweaks

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-metrics#11]
I had a good meeting with Gary and he likes the progress on the updated metrics! We discussed a few improvements. I mentioned these to @TaniaSchlatter as discussion topics for tomorrow's design meeting or a future design meeting.

- We need some way to better show off the exponential growth of file downloads (3.5 of 7 mil have been in the last year!). Just showing a year doesn't do it justice. If we stretch it further back we can really show a hockey stick. 
- We want to highlight not only the datasets in Dataverse installations, but the datasets that researchers can find and get access to using Dataverse. We should talk about the implementation here as we'd want to avoid double counting content for Dataverse installations that harvest from each other. 
- In the text at the bottom we should include the specific version that we added these metrics APIs in Dataverse (4.9, I believe)
- Next to the # of dataverses chart, we should consider having some definition of a dataverse.

**Comment by pdurbin** [comment]
When you change 12 months to 36 months, the plots look like this:

<img width="472" alt="Screen Shot 2019-04-24 at 10 49 49 AM" src="https://user-images.githubusercontent.com/21006/56669208-cb0c3c80-667e-11e9-91dc-f66522c7843f.png">

**Comment by pdurbin** [comment]
Here's the whole page:

![Dataverse_Metrics_-_2019-04-24_10 52 01](https://user-images.githubusercontent.com/21006/56669374-0c045100-667f-11e9-8fab-19dfe86ac8bb.png)

**Comment by TaniaSchlatter** [comment]
Thanks @pdurbin! Let's see about adding years to the x axis, taking out vertical grid lines if possible, and changing horizontal grid lines to white (à la Tufte).

**Comment by pdurbin** [comment]
@TaniaSchlatter sounds good and we'll put that in a release but for now @djbrooke said to go ahead and ask @donsizemore to update https://dataverse.org/metrics with the non-code change. I think in the meeting people could see on my screen that I asked at http://irclog.iq.harvard.edu/dataverse/2019-04-24#i_91632 and I **think** that he's done already. Here's how it looks now:

![Metrics_The_Dataverse_Project_-_Dataverse org_-_2019-04-24_12 03 45](https://user-images.githubusercontent.com/21006/56674975-09a6f480-6689-11e9-9bfa-435e402832a8.png)

I forgot to ask him to add https://data.inra.fr and their 77,665 datasets. We should probably figure out a process for config changes. For now I guess IRC works since Don is a regular. 😄 He's definitely on the "Who's who on chat.dataverse.org (#dataverse on irc.freenode.net)" spreadsheet linked from the topic in the channel: https://docs.google.com/spreadsheets/d/16h3jv24usMGq18495C-JA-yNcQCKiKDa65MTraNDd7k/edit?usp=sharing

**Comment by donsizemore** [comment]
I'm re-running with [https://data.inra.fr](https://data.inra.fr) back in the config file. Once we get better error handling in place they can all stay permanently.

**Comment by dlmurphy** [comment]
Created a branch for this issue and took care of the 3rd bullet point in the original post.

**Comment by djbrooke** [comment]
- We do have a way of determining if we're harvesting content from a Dataverse or other OAI-PMH server
-  We can carve out the harvesting piece as a separate issue and discuss in tech hours

**Comment by djbrooke** [comment]
@scolapasta - I forgot to ping you about the tech hours piece when I wrote the above note in Sprint Planning. This week or next would be good but I can push it out depending on your other priorities for the time.

**Comment by djbrooke** [comment]
Closing in favor of #17.
