### ISSUE TITLE
Show Github contribution metrics

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-metrics#16]
In a recent meeting, Gary suggested showing metrics regarding community contributions on the metrics page at dataverse.org/metrics. He noted the number of contributors as a compelling metric, but there may be some others as well. There's an API:

 https://developer.github.com/v3/repos/statistics/

We'd probably want some option to exclude these stats from view on the metrics application, as we've designed this to be useable for individual installations and groups as well.

**Comment by djbrooke** [comment]
Closing in favor of #17.

**Comment by pdurbin** [comment]
I'm opening this back up because from a feature perspective, this is a better description a nice small chunk that's part of #17 (which we are using to track the work).

@TaniaSchlatter and others, here's a screenshot of what I have so far in terms of how this metric could appear on the page. When you click, you get the contributors graph at https://github.com/IQSS/dataverse/graphs/contributors shown in the screenshot.

![Screen Shot 2019-05-29 at 12 57 24 PM](https://user-images.githubusercontent.com/21006/58576220-d28cab80-8211-11e9-80fb-6f34968aace6.png)

I know that for now we only want to show contributions from https://github.com/IQSS/dataverse but I've written the code to support multiple github repos in the future if we'd like to.

**Comment by pdurbin** [comment]
As I mentioned at standup, this task is completely independent of other work that needs to be done in #17 so I would love some code review on pull request #21 while I switch gears and look at other tasks.
