### ISSUE TITLE
not all installations enable Make Data Count

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-metrics#79]
For these installations a config option to disable display of the MDC rows would close a bunch of white space and quiesce the Payara log.

**Comment by PaulBoon** [comment]
@donsizemore As a workaround (not optimal) I added the following to the styles.css file: 

> /* Hide most of the MakeDataCount panel */
#mdcSection, .collapse.in.mdc-panel {
  display: none;
}

Stil some horizontal 'bar' is shown, but there is no way to select the parent panel in CSS.

**Comment by PaulBoon** [comment]
Would not be do difficult to implement a 'switch'; like adding `"makeDataCount" : false` to the config to disable and use a condition in the code like `if (config.hasOwnProperty("makeDataCount") && config.makeDataCount)` when trying to render it.  
Will have a look at it soon.

**Comment by PaulBoon** [comment]
@donsizemore Is this als a 'global metrics' problem, because I am only looking at the 'local metrics' right now?

**Comment by PaulBoon** [comment]
My PR #85 is working, just tested it. Some small thing though: Initially the page is rendered with the HTML element visible (need to scroll down on a standard monitor setup) because the 'hide' is done in a document ready handler. 
We might put the CSS 'workaround' code in comment to the css file, so you can reduce the potential 'flickering' if needed.

**Comment by qqmyers** [comment]
Closed by #85
