### ISSUE TITLE
Wrong links in tree selection when two or more levels deep

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse-metrics#81]
When viewing the 'local' metrics and there are several levels nested dataverses (collections) the links are wrong when more then one level deep. 
When selecting the link (when already one level deep) the resulting page is not showing the expected result, instead the  'parentAlias' URL parameter seems to be appended more than once. 

Susspected code is in `installationplots.js` 
The updateNames function does: 
`node.name = "<a href='" + window.location + "?parentAlias=" + node.alias + "'>" + node.alias + "</a>";`
Possible solution is to replace `window.location` with `window.location.href.split("?")[0]`

**Comment by qqmyers** [comment]
Seems like a reasonable fix. It looks like the error is whenever moving from one collection to another, i.e. whenever parentAlias is a param (is that only when going to a deeper collection due to how the tree widget works?) In any case. I think a PR for this makes sense.

**Comment by PaulBoon** [comment]
@qqmyers, @pdurbin Maybe it would be a good time to merge/close PRs and make a new release?

**Comment by pdurbin** [comment]
@PaulBoon fine by me but the code in this repo was pretty heavily rewritten by @qqmyers so I'll defer to him. It's good to know people are using it! https://dataverse.org/metrics is still running the older version of the code. (I assume you're using the "single installation" flavor rather than aggregating across installations.) Thanks for the pull request!

**Comment by qqmyers** [comment]
Closed by #82
